TITLE="Beej's Guide to Git"
SUBTITLE=""
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v0.18.0, Copyright © January 26, 2025"

GUIDE_ID=bggit
BGBSPD_BUILD_DIR?=../../bgbspd

WEB_IMAGES=$(wildcard img_*.svg img_*.png)

include $(BGBSPD_BUILD_DIR)/source.make
