TITLE="Beej's Guide to Git"
SUBTITLE=""
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v1.2.5, Copyright © February 20, 2025"

GUIDE_ID=bggit
BGBSPD_BUILD_DIR?=../../bgbspd

WEB_IMAGES=$(wildcard img_*.svg img_*.png)
EPUB_SVGS=$(wildcard img_*.svg)

include $(BGBSPD_BUILD_DIR)/source.make
